global:
  hosts:
    domain: gitlab.aliniacoding.com

  ingress:
    configureCertmanager: false  # Set to true if you are using cert-manager
    annotations:
      kubernetes.io/ingress.class: nginx
    class: "nginx"  # Ensure this matches the ingress.class annotation
    tls:
      enabled: true
      secretName: gitlab-cert  # Name of the secret that contains your TLS certificate

gitlab:
  gitlab-runner:
    install: true  # Enable if you need GitLab CI runners

nginx-ingress:
  enabled: true
  controller:
    ingressClassResource:
      name: "nginx"
      enabled: true
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        # Uncomment the line below and replace with your ACM certificate ARN if you are using AWS ACM
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${data.aws_acm_certificate.gitlab_cert.arn}"  # Use the ARN of your ACM certificate
      externalTrafficPolicy: "Local"  # Preserves the client source IP
